# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f95a96eee199c51323697513e6d1eaf605f9c81857e67118a651ba9ae4ff47a267a0c6ebe9b64036a772b8117f2bbea947c7b1f2fde7c3d34fd5c6df4456c415

test:
  secret_key_base: 447ce48b33fcf6040ab0bb4f0fe60a39a85ac69bb5521cec8b53e3dfa60da8465716ce2d5841f97a619ef2f5d040064d11f1654fade1d47181ec190e764f8ba8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
